tp2::Couverture Class Reference
#include <Couverture.h>
Public Member Functions
Couverture (std::ifstream &p_fichierEntree)
Constructeur à partir d'un fichier en entrée.
Couverture ()
Couverture & operator= (Couverture const &p_couverture)
void afficherVilles (std::vector< Ville > &p_vVilles)
Affiche une liste de villes de la couverture à l'écran.
void afficherVilles ()
bool villesAccessibles ()
Détermine si toutes les villes de la couverture sont accessibles à partir de n'importe où.
std::vector< Ville > villesCritiques ()
Trouve les points d'articulation de la couverture et les retourne.
std::vector< Ville > determinerMinParcours (const Ville &p_origine, const Ville &p_destination, int &p_duree)
Trouve le plus court chemin entre deux points en utilisant l'algorithme de Dijsktra et le retourne.
std::vector< Ville > bellManFord (const Ville &p_origine, const Ville &p_destination, int &p_duree)
Trouve le plus court chemin entre deux points en utilisant l'algorithme de Bellman-Ford et le retourne.
Graphe< Ville > const & reqGraphe () const
Le getter du graphe des villes.
Private Attributes
Graphe< Ville > m_graphe
Detailed Description
Definition at line 16 of file Couverture.h.
Constructor & Destructor Documentation
tp2::Couverture::Couverture (std::ifstream & p_fichierEntree)
Constructeur à partir d'un fichier en entrée.
Parameters
in p_fichierEntree pointeur sur le fichier contenant la liste des villes à charger ainsi que les liaisons.
Precondition
Il y a assez de mémoire pour charger toutes les ville de la liste.
Le fichier fichierEntree est ouvert corectement.
Postcondition
Le fichier fichierEntree n'est pas fermé par la fonction.
Si les préconditions sont respectées, les données de la couverture contenues dans le fichier en entrée sont organisées dans un graphe en mémoire.
Exceptions
bad_alloc si pas assez de mémoire contenir toute la liste du fichier.
logic_error si le fichier fichierEntree n'est pas ouvert correctement.
Definition at line 24 of file Couverture.cpp.
References Graphe< Objet >::ajouterArc(), Graphe< Objet >::ajouterSommet(), and m_graphe.
tp2::Couverture::Couverture ()
Definition at line 77 of file Couverture.cpp.
Member Function Documentation
void tp2::Couverture::afficherVilles (std::vector< Ville > & p_vVilles)
Affiche une liste de villes de la couverture à l'écran.
Parameters
in p_vVilles Une liste de villes dans un vector.
Postcondition
Le contenu de la liste p_vVilles est affiché.
Definition at line 90 of file Couverture.cpp.
void tp2::Couverture::afficherVilles ()
std::vector< Ville > tp2::Couverture::bellManFord (const Ville & p_origine, const Ville & p_destination, int & p_duree)
Trouve le plus court chemin entre deux points en utilisant l'algorithme de Bellman-Ford et le retourne.
Parameters
in p_origine la ville de l'origine.
in p_destination la ville de destination.
out p_duree le temps de vol total.
Returns
Un vecteur contenant la liste des villes a parcourir.
Precondition
Il y a assez de mémoire pour retourner les composantes du chemin.
Postcondition
Le temps de vol total est retourné, -1 s'il n'y a pas de chemin.
Le graphe original reste inchangé.
Exceptions
bad_alloc s'il n'y a pas assez de mémoire pour retourner le chemin.
logic_error si le sommet d'origine ou de destination n'existe pas.
Definition at line 178 of file Couverture.cpp.
References Graphe< Objet >::bellmanFord(), Graphe< Objet >::estVide(), and m_graphe.
std::vector< Ville > tp2::Couverture::determinerMinParcours (const Ville & p_origine, const Ville & p_destination, int & p_duree)
Trouve le plus court chemin entre deux points en utilisant l'algorithme de Dijsktra et le retourne.
Parameters
in p_origine la ville de l'origine.
in p_destination la ville de destination.
out p_duree le temps de vol total.
Returns
Un vecteur contenant la liste des villes a parcourir.
Precondition
Il y a assez de mémoire pour retourner les composantes du chemin.
Postcondition
Le temps de vol total est retourné, -1 s'il n'y a pas de chemin.
Le graphe original reste inchangé.
Exceptions
bad_alloc s'il n'y a pas assez de mémoire pour retourner le chemin.
logic_error si le sommet d'origine ou de destination n'existe pas.
Definition at line 149 of file Couverture.cpp.
References Graphe< Objet >::dijkstra(), Graphe< Objet >::estVide(), and m_graphe.
Couverture & tp2::Couverture::operator= (Couverture const & p_couverture)
Definition at line 80 of file Couverture.cpp.
References m_graphe, and reqGraphe().
Graphe< Ville > const & tp2::Couverture::reqGraphe () const
Le getter du graphe des villes.
Postcondition
L'instance courante n'est pas modifiée.
Returns
Le graphe des villes faisant partie de la couverture.
Definition at line 200 of file Couverture.cpp.
References m_graphe.
Referenced by operator=().
bool tp2::Couverture::villesAccessibles ()
Détermine si toutes les villes de la couverture sont accessibles à partir de n'importe où.
Precondition
La couverture est non vide.
Exceptions
logic_error si le graphe ne contient aucun sommet
Returns
VRAI si toute ville est accessible depuis une autre, sinon FAUX dans tous les autres cas.
Definition at line 109 of file Couverture.cpp.
References Graphe< Objet >::estFortementConnexe(), Graphe< Objet >::estVide(), and m_graphe.
std::vector< Ville > tp2::Couverture::villesCritiques ()
Trouve les points d'articulation de la couverture et les retourne.
Precondition
Il y a assez de mémoire pour retourner les points d'articulation.
Postcondition
Le graphe original reste inchangé.
Returns
La liste de tous les sommets d'articulation est retournée.
Exceptions
bad_alloc s'il n'y a pas assez de mémoire pour retourner les noms des sommets.
logic_error si la couverture ne contient aucune ville.
Definition at line 122 of file Couverture.cpp.
References Graphe< Objet >::estVide(), Graphe< Objet >::getPointsArticulation(), and m_graphe.
Member Data Documentation
Graphe<Ville> tp2::Couverture::m_graphe [private]
Definition at line 54 of file Couverture.h.
Referenced by bellManFord(), Couverture(), determinerMinParcours(), operator=(), reqGraphe(), villesAccessibles(), and villesCritiques().
The documentation for this class was generated from the following files:
Couverture.h
Couverture.cpp