tp2::Ville Class Reference
#include <Ville.h>
Public Member Functions
Ville ()
Ville (const std::string &p_nom, const std::string &p_codeAeroport)
Constructeur a partir du nom d'une ville et d'un code d'aeroport.
std::string reqCodeAeroport () const
std::string reqNom () const
bool operator== (const Ville &p_ville) const
Surcharge de l'opérateur == qui compare deux villes.
Private Attributes
std::string m_nom
std::string m_codeAeroport
Friends
std::ostream & operator<< (std::ostream &out, const Ville &p_ville)
Surcharge de l'opérateur << qui affiche les données d'une ville.
Detailed Description
Definition at line 15 of file Ville.h.
Constructor & Destructor Documentation
tp2::Ville::Ville ()
Definition at line 11 of file Ville.cpp.
tp2::Ville::Ville (const std::string & p_nom, const std::string & p_codeAeroport)
Constructeur a partir du nom d'une ville et d'un code d'aeroport.
Parameters
in p_nom nom d'une ville.
in p_codeAeroport code d'un aeroport.
Postcondition
Une ville est créée.
Definition at line 18 of file Ville.cpp.
Member Function Documentation
bool tp2::Ville::operator== (const Ville & p_ville) const
Surcharge de l'opérateur == qui compare deux villes.
Parameters
in Une ville a comparer avec l'instance courante.
Returns
vrai si les villes sont identiques, sinon faux.
Definition at line 25 of file Ville.cpp.
References m_codeAeroport, m_nom, reqCodeAeroport(), and reqNom().
std::string tp2::Ville::reqCodeAeroport () const [inline]
Definition at line 30 of file Ville.h.
References m_codeAeroport.
Referenced by tp2::operator<<(), and operator==().
std::string tp2::Ville::reqNom () const [inline]
Definition at line 36 of file Ville.h.
References m_nom.
Referenced by tp2::operator<<(), and operator==().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Ville & p_ville) [friend]
Surcharge de l'opérateur << qui affiche les données d'une ville.
Parameters
in Un stream.
in Une ville.
Postcondition
Les données de la ville sont affichées.
Definition at line 36 of file Ville.cpp.
Member Data Documentation
std::string tp2::Ville::m_codeAeroport [private]
Definition at line 27 of file Ville.h.
Referenced by operator==(), and reqCodeAeroport().
std::string tp2::Ville::m_nom [private]
Definition at line 26 of file Ville.h.
Referenced by operator==(), and reqNom().
The documentation for this class was generated from the following files:
Ville.h
Ville.cpp