Graphe< Objet > Class Template Reference
Classe représentant un graphe orienté, coloré dont les étiquettes sont des comparables.
#include <Graphe.h>
Classes
class Arc
Classe interne représentant un arc entre deux sommets dans le graphe.
class Sommet
Classe représentant un sommet dans un graphe.
Public Member Functions
Graphe ()
Constructeur par defaut.
Graphe (const Graphe &source)
Constructeur de copie.
~Graphe ()
Destructeur.
void ajouterSommet (int numero, const Objet &etiquette)
Ajout d'un sommet au graphe.
void enleverSommet (int numero)
Enlève un sommet du graphe ainsi que tous les arcs qui vont et partent de ce sommet.
void ajouterArc (int numOrigine, int numDestination, int cout)
Ajout d'un arc au graphe.
void enleverArc (int numOrigine, int numDestination)
Enlève un arc du graphe.
int nombreSommets () const
Retourne le nombre de sommets dans la liste des sommets.
bool estVide () const
Indique si la liste des sommets est vide.
std::vector< int > listerSommets () const
Retourne la liste des numéros des sommets dans un vecteur d'entiers.
std::vector< Objet > listerEtiquetteSommets () const
Retourne la liste des étiquettes des sommets dans un vecteur.
int getNumeroSommet (const Objet &etiquette) const
Retourne le numéro d'un sommet selon son etiquette.
bool sommetExiste (int numero) const
Retourne l'existence d'un sommet.
Objet getEtiquetteSommet (int numero) const
Retourne l'étiquette d'un sommet.
int ordreSortieSommet (int numero) const
Le sommet n'existe pas.
int ordreEntreeSommet (int numero) const
Retourne l'ordre d'entrée d'un sommet.
std::vector< int > listerSommetsAdjacents (int numeroSommetsAdjacents) const
Retourne la liste des numéros des sommets adjacents au sommet passé en argument dans un vecteur d'entiers.
bool arcExiste (int numOrigine, int numDestination) const
Retourne l'existence d'un arc.
int getCoutArc (int numOrigine, int numDestination) const
Retourne le coût d'un arc passé en argument.
const Graphe & operator= (const Graphe &source)
Surcharge de l'opérateur d'affectation.
Graphe fermetureGraphe () const
Déterminer la fermeture transitive du graphe.
bool estFortementConnexe () const
Détermine si le graphe est fortement connexe ou non.
void getComposantesFortementConnexes (std::vector< std::vector< Objet > > &composantes) const
Détermine les composantes fortement connexes et les mémorise dans un conteneur passé en paramètre.
int bellmanFord (const Objet &eOrigine, const Objet &eDestination, std::vector< Objet > &chemin)
Trouve le plus court chemin entre deux points en utilisant l'algorithme de Bellman-Ford et le retourne.
int dijkstra (const Objet &eOrigine, const Objet &eDestination, std::vector< Objet > &chemin)
Trouve le plus court chemin entre deux points en utilisant l'algorithme de Dijkstra et le retourne.
void getPointsArticulation (std::vector< Objet > &sommets)
Trouve les points d'articulation du graphe et les retourne.
Private Member Functions
Sommet * _getSommet (int numero) const
Trouve l'adresse d'un sommet à partir de son numéro.
Arc * _getArc (Sommet *sommet1, Sommet *sommet2) const
Arc * _getArc (int numOrigine, int numDestination) const
Trouve l'adresse d'un arc entre deux sommets.
void _detruireGraphe ()
void _copierGraphe (const Graphe &source)
Copie d'un graphe.
void _enleverSommet (Sommet *sommetAEnlever)
void _initPathFinding (const Objet &eOrigine, const Objet &eDestination, Sommet *&origine, Sommet *&destination)
void _recupererChemin (Sommet *destination, std::vector< Objet > &chemin)
bool _isArticulation (Graphe< Objet > graphe, Sommet *sommet)
Private Attributes
int nbSommets
Le nombre de sommets dans le graphe.
Sommet * listSommets
Liste des sommets du graphe.
Friends
template<class U >
std::ostream & operator<< (std::ostream &out, const Graphe< U > &g)
Detailed Description
template<typename Objet>class Graphe< Objet >
Classe représentant un graphe orienté, coloré dont les étiquettes sont des comparables.
Definition at line 19 of file Graphe.h.
Constructor & Destructor Documentation
template<typename Objet > Graphe< Objet >::Graphe ()
Constructeur par defaut.
Postcondition
Un graphe vide est créé.
Definition at line 90 of file Graphe.hpp.
template<typename Objet > Graphe< Objet >::Graphe (const Graphe< Objet > & source)
Constructeur de copie.
Parameters
in source La source du graphe à copier.
Precondition
Il y a assez de mémoire pour copier le graphe.
Exceptions
bad_alloc Il n'y a pas assez de mémoire pour copier le graphe.
Definition at line 101 of file Graphe.hpp.
template<typename Objet > Graphe< Objet >::~Graphe ()
Destructeur.
Postcondition
Le graphe est détruit.
Definition at line 137 of file Graphe.hpp.
Member Function Documentation
template<typename Objet > void Graphe< Objet >::_copierGraphe (const Graphe< Objet > & source) [private]
Copie d'un graphe.
Postcondition
Une copie profonde à partir du graphe source a été effectuée.
Parameters
in source Le graphe à copier.
Definition at line 111 of file Graphe.hpp.
References Graphe< Objet >::listSommets, Graphe< Objet >::Arc::m_cout, Graphe< Objet >::Arc::m_dest, Graphe< Objet >::Sommet::m_etiquette, Graphe< Objet >::Sommet::m_listeDest, Graphe< Objet >::Sommet::m_numero, Graphe< Objet >::Sommet::m_suivant, and Graphe< Objet >::Arc::m_suivDest.
template<typename Objet> void Graphe< Objet >::_detruireGraphe () [private]
template<typename Objet> void Graphe< Objet >::_enleverSommet (Sommet * sommetAEnlever) [private]
template<typename Objet > Graphe< Objet >::Arc * Graphe< Objet >::_getArc (int numOrigine, int numDestination) const [private]
Trouve l'adresse d'un arc entre deux sommets.
Postcondition
L'adresse de l'arc recherché est retournée, 0 si aucun arc n'a été trouvé.
Parameters
in origine L'adresse du sommet d'origine.
in destination L'adresse du sommet de destination.
Returns
L'adresse de l'arc trouvé entre le sommet d'origine et le sommet de destination.
Definition at line 164 of file Graphe.hpp.
References Graphe< Objet >::Arc::m_dest, Graphe< Objet >::Sommet::m_listeDest, Graphe< Objet >::Sommet::m_numero, and Graphe< Objet >::Arc::m_suivDest.
template<typename Objet> Arc* Graphe< Objet >::_getArc (Sommet * sommet1, Sommet * sommet2) const [private]
Referenced by Graphe< Objet >::estFortementConnexe(), and Graphe< Objet >::getComposantesFortementConnexes().
template<typename Objet > Graphe< Objet >::Sommet * Graphe< Objet >::_getSommet (int numero) const [private]
Trouve l'adresse d'un sommet à partir de son numéro.
Postcondition
L'adresse du sommet recherché est retournée.
Parameters
in numero Le numéro du sommet.
Definition at line 146 of file Graphe.hpp.
References Graphe< Objet >::Sommet::m_numero, and Graphe< Objet >::Sommet::m_suivant.
template<typename Objet> void Graphe< Objet >::_initPathFinding (const Objet & eOrigine, const Objet & eDestination, Sommet *& origine, Sommet *& destination) [private]
template<typename Objet> bool Graphe< Objet >::_isArticulation (Graphe< Objet > graphe, Sommet * sommet) [private]
Definition at line 738 of file Graphe.hpp.
References Graphe< Objet >::enleverSommet(), Graphe< Objet >::estFortementConnexe(), and Graphe< Objet >::Sommet::m_numero.
template<typename Objet> void Graphe< Objet >::_recupererChemin (Sommet * destination, std::vector< Objet > & chemin) [private]
template<typename Objet > void Graphe< Objet >::ajouterArc (int numOrigine, int numDestination, int cout)
Ajout d'un arc au graphe.
Parameters
in numOrigine Le numéro du sommet d'origine.
in numDestination Le numéro du sommet de destination.
in cout Le cout de l'arc.
Precondition
Les deux sommets doivent exister.
Postcondition
Un arc a été ajouté entre le sommet 'numeroOrigine' et le sommet 'numeroDestination'.
Exceptions
bad_alloc Pas assez de mémoire pour alloué le nouvel arc.
logic_error Un des deux sommets n'existe pas.
logic_error Il y a déjà un arc orienté entre ces deux sommets.
Definition at line 274 of file Graphe.hpp.
References Graphe< Objet >::Sommet::m_listeDest, and Graphe< Objet >::Arc::m_suivDest.
Referenced by tp2::Couverture::Couverture(), and Graphe< Objet >::fermetureGraphe().
template<typename Objet> void Graphe< Objet >::ajouterSommet (int numero, const Objet & etiquette)
Ajout d'un sommet au graphe.
Parameters
in etiquette Les donnees du sommet à ajouter.
in numero Le numero du sommet à ajouter.
Precondition
Il y a assez de mémoire pour ajouter un sommet.
Il n'y a aucun sommet avec le même numéro dans le graphe.
Postcondition
Un sommet contenant les informations passées en argument a été ajouté au Graphe.
Exceptions
bad_alloc Il n'y a pas assez de mémoire pour ajouter un sommet.
logic_error Il y a un sommet avec le même numéro dans le graphe.
Definition at line 186 of file Graphe.hpp.
References Graphe< Objet >::Sommet::m_numero, Graphe< Objet >::Sommet::m_precedent, and Graphe< Objet >::Sommet::m_suivant.
Referenced by tp2::Couverture::Couverture(), and Graphe< Objet >::fermetureGraphe().
template<typename Objet > bool Graphe< Objet >::arcExiste (int numOrigine, int numDestination) const
Retourne l'existence d'un arc.
Parameters
in numOrigine Le numéro du sommet d'origine.
in numDestination Le numéro du sommet de destination.
Returns
True si un arc existe entre les deux sommets, false autrement.
Precondition
Les sommets doivent appartenir au graphe.
Postcondition
Le graphe reste inchangé.
Exceptions
logic_error L'un ou l'autre, ou les 2 sommets ne font pas partie du graphe.
Definition at line 465 of file Graphe.hpp.
template<typename Objet> int Graphe< Objet >::bellmanFord (const Objet & eOrigine, const Objet & eDestination, std::vector< Objet > & chemin)
Trouve le plus court chemin entre deux points en utilisant l'algorithme de Bellman-Ford et le retourne.
Parameters
in eOrigine l'etiquette du sommet d'origine.
in eDestination l'etiquette du sommet de destination.
out chemin Un vector de type etiquette qui contient le chemin du parcours.
Returns
Le coût du parcours trouvé.
Precondition
Il y a assez de mémoire pour placer les composantes du chemin 'chemin'
Postcondition
Le cout total est retourné, -1 s'il n'y a pas de chemin
Le graphe original reste inchangé
La liste des étiquettes des sommets à parcourir est retournée dans le vector 'chemin'
Exceptions
bad_alloc Il n'y a pas assez de mémoire pour placer le chemin dans 'chemin'
logic_error Le sommet d'origine ou de destination n'existe pas
Definition at line 606 of file Graphe.hpp.
References Graphe< Objet >::Arc::m_cout, Graphe< Objet >::Sommet::m_cout, Graphe< Objet >::Arc::m_dest, Graphe< Objet >::Sommet::m_etiquette, Graphe< Objet >::Sommet::m_listeDest, Graphe< Objet >::Sommet::m_predecesseur, Graphe< Objet >::Sommet::m_suivant, and Graphe< Objet >::Arc::m_suivDest.
Referenced by tp2::Couverture::bellManFord().
template<typename Objet> int Graphe< Objet >::dijkstra (const Objet & eOrigine, const Objet & eDestination, std::vector< Objet > & chemin)
Trouve le plus court chemin entre deux points en utilisant l'algorithme de Dijkstra et le retourne.
Parameters
in eOrigine l'etiquette du sommet d'origine.
in eDestination l'etiquette du sommet de destination.
out chemin Un vector de type etiquette qui contient le chemin du parcours.
Returns
Le coût du parcours trouvé.
Precondition
Il y a assez de mémoire pour placer les composantes du chemin 'chemin'
Postcondition
Le cout total est retourné, -1 s'il n'y a pas de chemin
Le graphe original reste inchangé
La liste des étiquettes des sommets à parcourir est retournée dans le vector 'chemin'
Exceptions
bad_alloc Il n'y a pas assez de mémoire pour placer le chemin dans 'chemin'
logic_error Le sommet d'origine ou de destination n'existe pas
Definition at line 661 of file Graphe.hpp.
References Graphe< Objet >::Arc::m_cout, Graphe< Objet >::Sommet::m_cout, Graphe< Objet >::Arc::m_dest, Graphe< Objet >::Sommet::m_etat, Graphe< Objet >::Sommet::m_etiquette, Graphe< Objet >::Sommet::m_predecesseur, Graphe< Objet >::Sommet::m_suivant, and Graphe< Objet >::Arc::m_suivDest.
Referenced by tp2::Couverture::determinerMinParcours().
template<typename Objet > void Graphe< Objet >::enleverArc (int numOrigine, int numDestination)
Enlève un arc du graphe.
Parameters
in numOrigine Le numero du sommet d'origine.
in numDestination Le numéro du sommet de destination.
Precondition
Les deux sommets identifiés par leur numéro doivent appartenir au graphe.
Un arc reliant les deux sommets doit exister.
Postcondition
Le graphe contient un arc en moins
Exceptions
std::logic_error Un des deux sommets, ou les deux, n'existent pas.
std::logic_error Il n'y a pas d'arc entre les 2 sommets.
Definition at line 296 of file Graphe.hpp.
References Graphe< Objet >::Arc::m_dest, Graphe< Objet >::Sommet::m_listeDest, Graphe< Objet >::Sommet::m_numero, and Graphe< Objet >::Arc::m_suivDest.
template<typename Objet > void Graphe< Objet >::enleverSommet (int numero)
Enlève un sommet du graphe ainsi que tous les arcs qui vont et partent de ce sommet.
Parameters
in numero Le numéro du sommet à enlever.
Precondition
Il y a un sommet avec le numéro 'm_numero' dans le graphe.
Postcondition
Le sommet identifié par 'm_numero' a été enlevé du graphe.
Exceptions
logic_error Il n'y a aucun sommet avec le numéro 'm_numero' dans le graphe.
Definition at line 211 of file Graphe.hpp.
References Graphe< Objet >::Arc::m_dest, Graphe< Objet >::Sommet::m_listeDest, Graphe< Objet >::Sommet::m_numero, Graphe< Objet >::Sommet::m_precedent, Graphe< Objet >::Sommet::m_suivant, and Graphe< Objet >::Arc::m_suivDest.
Referenced by Graphe< Objet >::_isArticulation(), and Graphe< Objet >::getComposantesFortementConnexes().
template<typename Objet > bool Graphe< Objet >::estFortementConnexe () const
Détermine si le graphe est fortement connexe ou non.
Returns
true si le graphe est fortement connexe, false sinon
Postcondition
true est retourné si le graphe est fortement connexe, false est retourné sinon.
Definition at line 554 of file Graphe.hpp.
References Graphe< Objet >::_getArc(), and Graphe< Objet >::listerSommets().
Referenced by Graphe< Objet >::_isArticulation(), and tp2::Couverture::villesAccessibles().
template<typename Objet > bool Graphe< Objet >::estVide () const
Indique si la liste des sommets est vide.
Returns
True si le graphe ne contient pas de sommets, false autrement.
Postcondition
Le graphe reste inchangé.
Definition at line 332 of file Graphe.hpp.
Referenced by tp2::Couverture::bellManFord(), tp2::Couverture::determinerMinParcours(), tp2::Couverture::villesAccessibles(), and tp2::Couverture::villesCritiques().
template<typename Objet > Graphe< Objet > Graphe< Objet >::fermetureGraphe () const
Déterminer la fermeture transitive du graphe.
Precondition
Le graphe est correctement initialisé.
Postcondition
La fermeture transitive du graphe est retournée.
Le graphe original reste inchangé.
Exceptions
bad_alloc si pas assez de mémoire application de l'algorithme de Floyd-Warshall
Definition at line 508 of file Graphe.hpp.
References Graphe< Objet >::ajouterArc(), Graphe< Objet >::ajouterSommet(), Graphe< Objet >::Sommet::m_etiquette, Graphe< Objet >::Sommet::m_numero, and Graphe< Objet >::Sommet::m_suivant.
template<typename Objet> void Graphe< Objet >::getComposantesFortementConnexes (std::vector< std::vector< Objet > > & composantes) const
Détermine les composantes fortement connexes et les mémorise dans un conteneur passé en paramètre.
Parameters
in composantes Les composantes du graphe.
Precondition
Il y a assez de mémoire pour placer les composantes fortements connexes dans 'composantes'.
Postcondition
Les composantes fortement connexes du graphe sont placées dans 'composantes'.
Exceptions
Il n'y a pas assez de mémoire pour placer les composantes fortements connexes dans 'composantes'.
Definition at line 571 of file Graphe.hpp.
References Graphe< Objet >::_getArc(), Graphe< Objet >::enleverSommet(), Graphe< Objet >::listSommets, Graphe< Objet >::Arc::m_dest, Graphe< Objet >::Sommet::m_etiquette, Graphe< Objet >::Sommet::m_listeDest, Graphe< Objet >::Sommet::m_numero, Graphe< Objet >::Sommet::m_suivant, and Graphe< Objet >::Arc::m_suivDest.
template<typename Objet > int Graphe< Objet >::getCoutArc (int numOrigine, int numDestination) const
Retourne le coût d'un arc passé en argument.
Parameters
in numOrigine Le numéro du sommet d'origine.
in numDestination Le numéro du sommet de destination.
Returns
Le coût de l'arc entre deux sommets.
Precondition
L'arc doit exister.
Postcondition
Le graphe reste inchangé.
Exceptions
logic_error Le sommet source et/ou destination n'existent pas.
logic_error L'arc n'existe pas.
Definition at line 481 of file Graphe.hpp.
template<typename Objet > Objet Graphe< Objet >::getEtiquetteSommet (int numero) const
Retourne l'étiquette d'un sommet.
Parameters
in numero Le numéro du sommet.
Returns
Le nom du sommet recherché.
Precondition
Le sommet doit exister.
Exceptions
logic_error Il n'y a pas de sommets dans le graphe.
logic_error Le sommet n'existe pas.
Definition at line 405 of file Graphe.hpp.
template<typename Objet> int Graphe< Objet >::getNumeroSommet (const Objet & etiquette) const
Retourne le numéro d'un sommet selon son etiquette.
Parameters
in etiquette L'étiquette d'un sommet.
Returns
Le numéro du sommet recherché
Precondition
Le sommet doit faire partie du graphe.
Postcondition
Le graphe reste inchangé.
Exceptions
logic_error Le sommet n'existe pas.
Definition at line 376 of file Graphe.hpp.
References Graphe< Objet >::Sommet::m_etiquette, Graphe< Objet >::Sommet::m_numero, and Graphe< Objet >::Sommet::m_suivant.
template<typename Objet> void Graphe< Objet >::getPointsArticulation (std::vector< Objet > & sommets)
Trouve les points d'articulation du graphe et les retourne.
Parameters
out sommets Un vector de type Objet qui contient tous les sommets d'articulation.
Precondition
Il y a assez de mémoire pour placer les sommets dans 'sommets'
Postcondition
La liste de tous les sommets d'articulation sont retournés dans le vector 'sommets'
Le graphe original reste inchangé
Definition at line 723 of file Graphe.hpp.
References Graphe< Objet >::listSommets, Graphe< Objet >::Sommet::m_etiquette, and Graphe< Objet >::Sommet::m_suivant.
Referenced by tp2::Couverture::villesCritiques().
template<typename Objet > std::vector< Objet > Graphe< Objet >::listerEtiquetteSommets () const
Retourne la liste des étiquettes des sommets dans un vecteur.
Returns
Un vector de type Objet qui contient une liste de toutes les étiquettes des sommets.
Postcondition
Le graphe reste inchangé.
Definition at line 357 of file Graphe.hpp.
References Graphe< Objet >::Sommet::m_etiquette, and Graphe< Objet >::Sommet::m_suivant.
template<typename Objet > std::vector< int > Graphe< Objet >::listerSommets () const
Retourne la liste des numéros des sommets dans un vecteur d'entiers.
Returns
Un vector de type int qui contient une liste de tous les numéros des sommets.
Postcondition
Le graphe reste inchangé.
Definition at line 341 of file Graphe.hpp.
References Graphe< Objet >::Sommet::m_numero, and Graphe< Objet >::Sommet::m_suivant.
Referenced by Graphe< Objet >::estFortementConnexe().
template<typename Objet > std::vector< int > Graphe< Objet >::listerSommetsAdjacents (int numeroSommetsAdjacents) const
Retourne la liste des numéros des sommets adjacents au sommet passé en argument dans un vecteur d'entiers.
Parameters
in numeroSommetsAdjacents Le numéro du sommet dont on cherche les sommets adjacents.
Returns
Un vector de type int qui contient une liste de tous les numéros des sommets adjacents au sommet demandé.
Precondition
Le sommet doit appartenir au graphe.
Postcondition
Le graphe reste inchangé.
Exceptions
logic_error si le sommet n'existe pas.
Definition at line 442 of file Graphe.hpp.
References Graphe< Objet >::Arc::m_dest, Graphe< Objet >::Sommet::m_listeDest, and Graphe< Objet >::Arc::m_suivDest.
template<typename Objet > int Graphe< Objet >::nombreSommets () const
Retourne le nombre de sommets dans la liste des sommets.
Returns
Le nombre de sommets dans le graphe.
Postcondition
Le graphe reste inchangé.
Definition at line 323 of file Graphe.hpp.
template<typename Objet > const Graphe< Objet > & Graphe< Objet >::operator= (const Graphe< Objet > & source)
Surcharge de l'opérateur d'affectation.
Parameters
in source Le graphe à copier.
Precondition
Il doit y avoir assez de mémoire.
Postcondition
Le graphe a un contenu identique à 'source'.
Exceptions
bad_alloc S'il n'y a pas assez de mémoire.
Definition at line 496 of file Graphe.hpp.
template<typename Objet > int Graphe< Objet >::ordreEntreeSommet (int numero) const
Retourne l'ordre d'entrée d'un sommet.
Parameters
in Le numéro du sommet.
Returns
L'odre d'entrée d'un sommet.
Precondition
Le sommet doit exister
Postcondition
Le graphe reste inchangé.
Exceptions
logic_error Le sommet n'existe pas.
Definition at line 430 of file Graphe.hpp.
template<typename Objet > int Graphe< Objet >::ordreSortieSommet (int numero) const
Le sommet n'existe pas.
Parameters
in Le numéro du sommet.
Returns
L'odre de sortie d'un sommet.
Precondition
Le sommet doit exister.
Exceptions
logic_error Le sommet n'existe pas.
Definition at line 418 of file Graphe.hpp.
template<typename Objet > bool Graphe< Objet >::sommetExiste (int numero) const
Retourne l'existence d'un sommet.
Parameters
in numero Le numéro du sommet.
Returns
True si le sommet existe, false autrement.
Postcondition
Le graphe reste inchangé.
Definition at line 393 of file Graphe.hpp.
Friends And Related Function Documentation
template<typename Objet> template<class U > std::ostream& operator<< (std::ostream & out, const Graphe< U > & g) [friend]
Member Data Documentation
template<typename Objet> Sommet* Graphe< Objet >::listSommets [private]
Liste des sommets du graphe.
Definition at line 159 of file Graphe.h.
Referenced by Graphe< Objet >::_copierGraphe(), Graphe< Objet >::getComposantesFortementConnexes(), and Graphe< Objet >::getPointsArticulation().
template<typename Objet> int Graphe< Objet >::nbSommets [private]
Le nombre de sommets dans le graphe.
Definition at line 158 of file Graphe.h.
The documentation for this class was generated from the following files:
Graphe.h
Graphe.hpp